version: '3.3'
services:
    portainer-ce:
        ports:
            - '47103:9443'
        container_name: portainer
        restart: unless-stopped
        volumes:
            - './data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: 'portainer/portainer-ce:latest'