services:
  miniflux:
    image: miniflux/miniflux:latest
    env_file: /var/data/config/miniflux/miniflux.env
    ports:
      - "47108:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/miniflux", "-healthcheck", "auto"]
  db:
    image: postgres:15
    env_file: /var/data/config/miniflux/miniflux.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "minifluxdb"]
      interval: 10s
      start_period: 30s