version: '3.3'
services:
    focalboard:
        image: mattermost/focalboard
        container_name: focalboard
        ports:
          - '47106:8000'
        volumes:
          - ./data:/data
        restart: unless-stopped