version: '3.3'
services:
    focalboard:
        image: mattermost/focalboard
        container_name: focalboard
        ports:
          - '47106:8000'
        volumes:
          - ./data:/data
<<<<<<< HEAD
        restart: unless-stopped
=======
        restart: unless-stopped
>>>>>>> b1e84ba0aaf7599eac131ed4d5594438b80b0956
