name: local-lang-tool
services:
    docker-languagetool:
        container_name: languagetool
        cap_drop:
            - ALL
        user: 65534:65534
        read_only: true
        volumes:
            - '/tmp:/languagetool/tmp'
            - './data/ngrams:/ngrams'
        ports:
            - 127.0.0.1:47109:8010
        deploy:
            resources:
                limits:
                    memory: 2g
        memswap_limit: 2.5g
        environment:
            - EXTRAOPTIONS=-Xmx382M
        image: silviof/docker-languagetool:latest

