name: <your project name>
services:
    docker-languagetool:
        container_name: languagetool
        cap_drop:
            - ALL
        user: 65534:65534
        read_only: true
        volumes:
            - type: bind
              src: /tmp/languagetool/tmp
              dst: /tmp
            - './data/ngrams:/ngrams'
        ports:
            - 127.0.0.1:8010:8010
        deploy:
            resources:
                limits:
                    memory: 412m
        memswap_limit: 500m
        environment:
            - EXTRAOPTIONS=-Xmx382M
        image: silviof/docker-languagetool:latest
